
class Task:
    # Task is only going to require a task name, description is going to be optional
    # id should only be generated by the TaskManager
    def __init__(self, task_name, id):
        self.task_name = task_name
        self.description = None
        self.id = id

    def set_task_name(self, name):
        self.task_name = name

    def set_description(self, description):
        self.description = description

    def get_task_name(self):
        return self.task_name

    def get_description(self):
        return self.description
    
    def get_id(self):
        return self.id